### ISSUE TITLE
Is this up-to-date with the milligram/milligram repo?

### ISSUE THREAD

**Issue by joekaiser** [milligram/milligram-scss#11]
I have been enjoying milligram, and I was pleasantly surprised to find there is an scss version. I noticed the  last commit to this repository is "a month ago" and I was wondering how this version compares to the other one.

**Comment by cjpatoilo** [comment]
Hi @joekaiser 

I am very happy for your interest in [Milligram](http://milligram.github.io/). Saturday I will make the latest revisions in the code and will launch the next version of all repository, included the SCSS version.

**Comment by joekaiser** [comment]
Great, thanks!
