### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by avetisk** [milligram/milligram-scss#12]
It would be great to bump a new version as the engine is now set to `^7.0.0` on `master` branch.

Currently I need to systematically use `--ignore-engines` with `yarn`.

**Comment by avetisk** [comment]
Guys, I know it's Christmas and all, but can't you just publish it...?

**Comment by cjpatoilo** [comment]
Hi @avetisk Sorry for delay. This problem went up without my noticing. I will be closing a new version with some updates and corrections that you reported as soon as possible. My wish is to get everything ready by the end of the week.

Thank you for reporting this issue. I appreciate that. <3

**Comment by knpwrs** [comment]
Not to be "that guy" but this is still an issue.

**Comment by antid0te** [comment]
You can add module from github with `yarn add https://github.com/milligram/milligram-scss.git`
It will clone the master as your module.

**Comment by cjpatoilo** [comment]
@avetisk @knpwrs @antid0te Guys, for now I will close this issue. Feel free to reopen this issue if this doesn't do the trick for you.
