### ISSUE TITLE
Downloading via bower doesn't work

### ISSUE THREAD

**Issue by hslzr** [milligram/milligram-scss#4]
I typed `bower install milligram-scss` but got normal milligram (`.css` & `.min.css` instead). The `npm install` version works fine, though.

**Comment by GabrielGil** [comment]
This is due the following mismatch:

```
bower mismatch      Version declared in the json (0.0.1) is different than the resolved one `(1.0.0)
```

The version 1.0.0 tagged on GitHub contains a bower.json file with a declared version 0.0.1.
I suggest creating a new tag 1.0.1 with an appropriate declaration.

**Comment by GabrielGil** [comment]
You can also, temporarely usethis in your `bower.json`.

``` json
"dependencies": {
    "milligram-scss": "master"
}
```

**Comment by webmarkelov** [comment]
```
"dependencies": {
    "milligram-scss": "@milligram/milligram-scss#master"
  },
```
`bower install --save @milligram/milligram-scss#master`

**Comment by mohdhazwan** [comment]
point to master 
`bower install --save-dev milligram-sass#master`

**Comment by cjpatoilo** [comment]
@hslzr @GabrielGil @mohdhazwan sorry guys!!!

I've been out for a long time. I am updating all repositories during these days and everything will return to normal.
